/*
 * This file is generated by jOOQ.
 */
package io.tcj.jooq.tables.records;


import io.tcj.jooq.tables.Kv;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KvRecord extends UpdatableRecordImpl<KvRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kv.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>kv.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kv.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>kv.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>kv.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>kv.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>kv.feed_sync_id</code>.
     */
    public void setFeedSyncId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>kv.feed_sync_id</code>.
     */
    public Long getFeedSyncId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>kv.shard</code>.
     */
    public void setShard(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>kv.shard</code>.
     */
    public Integer getShard() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kv.ns</code>.
     */
    public void setNs(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kv.ns</code>.
     */
    public String getNs() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kv.k</code>.
     */
    public void setK(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kv.k</code>.
     */
    public String getK() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kv.v</code>.
     */
    public void setV(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>kv.v</code>.
     */
    public String getV() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KvRecord
     */
    public KvRecord() {
        super(Kv.KV);
    }

    /**
     * Create a detached, initialised KvRecord
     */
    public KvRecord(Long id, LocalDateTime createdAt, LocalDateTime updatedAt, Long feedSyncId, Integer shard, String ns, String k, String v) {
        super(Kv.KV);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setFeedSyncId(feedSyncId);
        setShard(shard);
        setNs(ns);
        setK(k);
        setV(v);
        resetChangedOnNotNull();
    }
}
