/*
 * This file is generated by jOOQ.
 */
package io.tcj.jooq.tables.records;


import io.tcj.jooq.tables.Kv;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KvRecord extends TableRecordImpl<KvRecord> implements Record9<Integer, LocalDateTime, LocalDateTime, Integer, Long, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.kv.id</code>.
     */
    public KvRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.kv.created_at</code>.
     */
    public KvRecord setCreatedAt(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.kv.updated_at</code>.
     */
    public KvRecord setUpdatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.kv.version</code>.
     */
    public KvRecord setVersion(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.kv.feed_sync_id</code>.
     */
    public KvRecord setFeedSyncId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.feed_sync_id</code>.
     */
    public Long getFeedSyncId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.kv.shard</code>.
     */
    public KvRecord setShard(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.shard</code>.
     */
    public Integer getShard() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.kv.ns</code>.
     */
    public KvRecord setNs(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.ns</code>.
     */
    public String getNs() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.kv.k</code>.
     */
    public KvRecord setK(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.k</code>.
     */
    public String getK() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.kv.v</code>.
     */
    public KvRecord setV(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.kv.v</code>.
     */
    public String getV() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, LocalDateTime, LocalDateTime, Integer, Long, Integer, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, LocalDateTime, LocalDateTime, Integer, Long, Integer, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Kv.KV.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Kv.KV.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Kv.KV.UPDATED_AT;
    }

    @Override
    public Field<Integer> field4() {
        return Kv.KV.VERSION;
    }

    @Override
    public Field<Long> field5() {
        return Kv.KV.FEED_SYNC_ID;
    }

    @Override
    public Field<Integer> field6() {
        return Kv.KV.SHARD;
    }

    @Override
    public Field<String> field7() {
        return Kv.KV.NS;
    }

    @Override
    public Field<String> field8() {
        return Kv.KV.K;
    }

    @Override
    public Field<String> field9() {
        return Kv.KV.V;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public Integer component4() {
        return getVersion();
    }

    @Override
    public Long component5() {
        return getFeedSyncId();
    }

    @Override
    public Integer component6() {
        return getShard();
    }

    @Override
    public String component7() {
        return getNs();
    }

    @Override
    public String component8() {
        return getK();
    }

    @Override
    public String component9() {
        return getV();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public Integer value4() {
        return getVersion();
    }

    @Override
    public Long value5() {
        return getFeedSyncId();
    }

    @Override
    public Integer value6() {
        return getShard();
    }

    @Override
    public String value7() {
        return getNs();
    }

    @Override
    public String value8() {
        return getK();
    }

    @Override
    public String value9() {
        return getV();
    }

    @Override
    public KvRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public KvRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public KvRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public KvRecord value4(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public KvRecord value5(Long value) {
        setFeedSyncId(value);
        return this;
    }

    @Override
    public KvRecord value6(Integer value) {
        setShard(value);
        return this;
    }

    @Override
    public KvRecord value7(String value) {
        setNs(value);
        return this;
    }

    @Override
    public KvRecord value8(String value) {
        setK(value);
        return this;
    }

    @Override
    public KvRecord value9(String value) {
        setV(value);
        return this;
    }

    @Override
    public KvRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, Integer value4, Long value5, Integer value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KvRecord
     */
    public KvRecord() {
        super(Kv.KV);
    }

    /**
     * Create a detached, initialised KvRecord
     */
    public KvRecord(Integer id, LocalDateTime createdAt, LocalDateTime updatedAt, Integer version, Long feedSyncId, Integer shard, String ns, String k, String v) {
        super(Kv.KV);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setFeedSyncId(feedSyncId);
        setShard(shard);
        setNs(ns);
        setK(k);
        setV(v);
    }
}
