/*
 * This file is generated by jOOQ.
 */
package io.tcj.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kv implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer       id;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;
    private final Integer       version;
    private final Long          feedSyncId;
    private final Integer       shard;
    private final String        ns;
    private final String        k;
    private final String        v;

    public Kv(Kv value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.version = value.version;
        this.feedSyncId = value.feedSyncId;
        this.shard = value.shard;
        this.ns = value.ns;
        this.k = value.k;
        this.v = value.v;
    }

    public Kv(
        Integer       id,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        Integer       version,
        Long          feedSyncId,
        Integer       shard,
        String        ns,
        String        k,
        String        v
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.version = version;
        this.feedSyncId = feedSyncId;
        this.shard = shard;
        this.ns = ns;
        this.k = k;
        this.v = v;
    }

    /**
     * Getter for <code>public.kv.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.kv.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.kv.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Getter for <code>public.kv.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>public.kv.feed_sync_id</code>.
     */
    public Long getFeedSyncId() {
        return this.feedSyncId;
    }

    /**
     * Getter for <code>public.kv.shard</code>.
     */
    public Integer getShard() {
        return this.shard;
    }

    /**
     * Getter for <code>public.kv.ns</code>.
     */
    public String getNs() {
        return this.ns;
    }

    /**
     * Getter for <code>public.kv.k</code>.
     */
    public String getK() {
        return this.k;
    }

    /**
     * Getter for <code>public.kv.v</code>.
     */
    public String getV() {
        return this.v;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Kv (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(version);
        sb.append(", ").append(feedSyncId);
        sb.append(", ").append(shard);
        sb.append(", ").append(ns);
        sb.append(", ").append(k);
        sb.append(", ").append(v);

        sb.append(")");
        return sb.toString();
    }
}
