/*
 * This file is generated by jOOQ.
 */
package io.tcj.jooq;


import io.tcj.jooq.tables.Kv;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index KV_IDX_CA = Internal.createIndex(DSL.name("idx_ca"), Kv.KV, new OrderField[] { Kv.KV.CREATED_AT }, false);
}
