/*
 * This file is generated by jOOQ.
 */
package io.tcj.jooq;


import io.tcj.jooq.tables.Kv;
import io.tcj.jooq.tables.records.KvRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<KvRecord> U_NS_K = Internal.createUniqueKey(Kv.KV, DSL.name("u_ns_k"), new TableField[] { Kv.KV.NS, Kv.KV.K }, true);
}
