/*
 * This file is generated by jOOQ.
 */
package io.tcj.jooq;


import io.tcj.jooq.tables.Kv;
import io.tcj.jooq.tables.records.KvRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<KvRecord> KEY_KV_PRIMARY = Internal.createUniqueKey(Kv.KV, DSL.name("KEY_kv_PRIMARY"), new TableField[] { Kv.KV.ID }, true);
    public static final UniqueKey<KvRecord> KEY_KV_U_FSI = Internal.createUniqueKey(Kv.KV, DSL.name("KEY_kv_u_fsi"), new TableField[] { Kv.KV.FEED_SYNC_ID }, true);
    public static final UniqueKey<KvRecord> KEY_KV_U_NS_K = Internal.createUniqueKey(Kv.KV, DSL.name("KEY_kv_u_ns_k"), new TableField[] { Kv.KV.NS, Kv.KV.K }, true);
}
