/*
 * This file is generated by jOOQ.
 */
package io.tcj.jooq;


import io.tcj.jooq.tables.Kv;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.kv</code>.
     */
    public static final Kv KV = Kv.KV;
}
